// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("user")]
	public class User
	{
		[Column("id"       , IsPrimaryKey = true )] public Guid    Id       { get; set; } // uuid
		[Column("username" , CanBeNull    = false)] public string  Username { get; set; } = null!; // character varying
		[Column("total_due"                      )] public decimal TotalDue { get; set; } // money
	}
}
