// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Data;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

#pragma warning disable 1573, 1591
#nullable enable

namespace Akkatecture.Example.RentAStream.Web.Models
{
	public partial class RentastreamDb : DataConnection
	{
		public RentastreamDb()
		{
			InitDataContext();
		}

		public RentastreamDb(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public RentastreamDb(LinqToDBConnectionOptions<RentastreamDb> options)
			: base(options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Account> Accounts => this.GetTable<Account>();
	}

	public static partial class ExtensionMethods
	{
		#region Table Extensions
		public static Account? Find(this ITable<Account> table, int id)
		{
			return table.FirstOrDefault(e => e.Id == id);
		}

		public static Task<Account?> FindAsync(this ITable<Account> table, int id, CancellationToken cancellationToken = default)
		{
			return table.FirstOrDefaultAsync(e => e.Id == id, cancellationToken);
		}
		#endregion
	}
}
