// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Configuration;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	public partial class RentastreamDb : DataConnection
	{
		#region Schemas
		public void InitSchemas()
		{
			Projections = new ProjectionsSchema.DataContext(this);
			Config = new ConfigSchema.DataContext(this);
		}

		public ProjectionsSchema.DataContext Projections { get; set; } = null!;
		public ConfigSchema.DataContext      Config      { get; set; } = null!;
		#endregion

		public RentastreamDb()
		{
			InitSchemas();
			InitDataContext();
		}

		public RentastreamDb(string configuration)
			: base(configuration)
		{
			InitSchemas();
			InitDataContext();
		}

		public RentastreamDb(LinqToDBConnectionOptions<RentastreamDb> options)
			: base(options)
		{
			InitSchemas();
			InitDataContext();
		}

		partial void InitDataContext();
	}
}
